In [73]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pandas as pd 

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn
# Load dataset
# X, y = load_iris(return_X_y=True)abs
df = pd.read_csv("/Users/ss/Downloads/covid_toy.csv")


numerical_col = ['age','fever']
categorical_col = ['gender','cough','city']

In [74]:
print("Numerical:", numerical_col)
print("Categorical:", categorical_col)

Numerical: ['age', 'fever']
Categorical: ['gender', 'cough', 'city']

In [75]:
from sklearn.model_selection import train_test_split

# Explicitly map categories to specific integer
df['has_covid'] = df['has_covid'].map({'No': 0, 'Yes': 1})

X = df.drop("has_covid", axis=1)
y = df['has_covid']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [77]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(
        strategy="median"
    )),

    ("scaler", StandardScaler())
])

# categorical pipeline 
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])
     

preprocessor = ColumnTransformer([
    ("numerical", numeric_pipeline, numerical_col),
    ("categorical", categorical_pipeline, categorical_col)
])
df.head()

   age  gender  fever cough     city  has_covid
0   60    Male  103.0  Mild  Kolkata          0
1   27    Male  100.0  Mild    Delhi          1
2   42    Male  101.0  Mild    Delhi          0
3   31  Female   98.0  Mild  Kolkata          0
4   65  Female  101.0  Mild   Mumbai          0

In [70]:

# print(X_train_processed.shape)
# print(X_test_processed.shape)

In [63]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print(X_train_processed.shape)
print(X_test_processed.shape)

(80, 10)
(20, 10)

In [62]:


# Base model
base_model = DecisionTreeClassifier(random_state=42)

# Bagging model
model = BaggingClassifier(
    estimator=base_model,
    n_estimators=10,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

ValueError: could not convert string to float: 'Male'

In [53]:
df.head()

   age  gender  fever cough     city  has_covid
0   60    Male  103.0  Mild  Kolkata          0
1   27    Male  100.0  Mild    Delhi          1
2   42    Male  101.0  Mild    Delhi          0
3   31  Female   98.0  Mild  Kolkata          0
4   65  Female  101.0  Mild   Mumbai          0

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
df = pd.read_csv("/Users/ss/Downloads/covid_toy.csv")
# Features and target
X = df.drop(columns=["has_covid"])
y = df["has_covid"].map({"No": 0, "Yes": 1})

# Remove rows with missing target values
valid = y.notna()
X = X.loc[valid]
y = y.loc[valid]

# Column names
numerical_col = ["age", "fever"]
categorical_col = ["gender", "cough", "city"]

# Preprocessing pipelines
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numerical_col),
    ("cat", categorical_pipeline, categorical_col)
])

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Preprocess
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

# Bagging classifier
model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=10,
    random_state=42
)

model.fit(X_train_processed, y_train)

y_pred = model.predict(X_test_processed)

print("Accuracy:", accuracy_score(y_test, y_pred))