In [ ]:
# Ensemble learninig is a machine learning technique that involves combining multiple individual models
# know as base learners to make predictions individual models , know as base learners  to make
# predictions or decsions the main idea behind ensemble learning  is that by combining the predictions of
# multiple models the overall performance can be improved compared to using a single

In [ ]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
x,y = make_classification(n_samples=1000,n_features=20,random_state=42)

In [ ]:
x_train , x_test,y_train,y_test =train_test_split(x,y, test_size=0.2, random_state= 42)

In [ ]:
base_learners = []

In [ ]:
num_base_learners = 10

In [ ]:
# for i in range(num_base_learners):
#   bootstrap_indices = np.random.choice(len(x_train),size = len(x_train),replace= True)
#   x_bootstrap = x_train[bootstrap_indices]
#   y_bootstrap = y_train[bootstrap_indices]

In [ ]:
# from sklearn.ensemble import RandomForestClassifier
# import numpy as np

# base_learners = []   # <-- important

# base_learner = RandomForestClassifier(
#     n_estimators=10,
#     random_state=42
# )

# base_learner.fit(x_bootstrap, y_bootstrap)

# base_learners.append(base_learner)

# base_predictions = []

# for base_learner in base_learners:
#     y_pred = base_learner.predict(x_test)
#     base_predictions.append(y_pred)

# ensemble_predictions = np.round(
#     np.mean(base_predictions, axis=0)
# )

In [ ]:
# accuracy = accuracy_score(y_test,ensemble_predictions)
# print("Ensemble Accuracy :", accuracy)

Ensemble Accuracy : 0.855

In [ ]:
df = pd.read_csv("/content/covid_toy - covid_toy (1).csv")

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# Gender ko numerical
df["gender"] = df["gender"].map({
    "Male": 1,
    "Female": 0
})

# Cough ko numerical
df["cough"] = df["cough"].map({
    "Mild": 1,
    "Strong": 2
})

# City ko numerical using One-Hot Encoding
df = pd.get_dummies(
    df,
    columns=["city"],
    dtype=int
)

print(df.head())

   age  gender  fever  ...  city_Delhi city_Kolkata  city_Mumbai
0   60       1  103.0  ...           0            1            0
1   27       1  100.0  ...           1            0            0
2   42       1  101.0  ...           1            0            0
3   31       0   98.0  ...           0            1            0
4   65       0  101.0  ...           0            0            1

[5 rows x 9 columns]

In [ ]:
df['has_covid'] = df['has_covid'].dropna()

In [ ]:
df['has_covid'].isna().sum()

np.int64(0)

In [ ]:
df['has_covid'] = df['has_covid'].map({
    "Yes": 1,
    "No": 0
})

In [ ]:
df['has_covid']

0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 100, dtype: int64

In [ ]:
X = df.drop(columns=["has_covid"])
Y = df['has_covid']

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size= 0.2,random_state= 42)

In [ ]:
base_learners = []
num_base_learners = 10

In [ ]:
for i in range(num_base_learners):

    bootstrap_indices = np.random.choice(
        len(X_train),
        size=len(X_train),
        replace=True
    )

    x_bootstrap = X_train.iloc[bootstrap_indices]

    y_bootstrap = Y_train.iloc[bootstrap_indices]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np

base_learners = []   # <-- important

base_learner = RandomForestClassifier(
    n_estimators=10,
    random_state=42
)

base_learner.fit(x_bootstrap, y_bootstrap)

base_learners.append(base_learner)

base_predictions = []

for base_learner in base_learners:
    y_pred = base_learner.predict(X_test)
    base_predictions.append(y_pred)

ensemble_predictions = np.round(
    np.mean(base_predictions, axis=0)
)

In [ ]:
accuracy = accuracy_score(Y_test,ensemble_predictions)
print("covid dataset accuracy ---> ", accuracy)

covid dataset accuracy --->  0.45